"use client";

import Image from "next/image";
import { Footer } from "@/components/Footer";
import { ActionButton } from "@/components/ActionButton";
import { SkillPassportCard } from "@/components/SkillPassportCard";
import {
  BookMarked,
  Shield,
  Users,
  BarChart3,
  CheckCircle,
  Database,
  Globe,
  RefreshCcw,
} from "lucide-react";
import { motion } from "framer-motion";
import { useInView } from "framer-motion";
import { useRef, useState } from "react";

/* ─── small helper: reveal-wipe text animation ─── */
function RevealText({
  children,
  className,
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-10% 0px" });
  return (
    <div className="overflow-hidden" ref={ref}>
      <motion.div
        className={className}
        initial={{ y: "105%" }}
        animate={isInView ? { y: "0%" } : {}}
        transition={{ duration: 0.65, delay, ease: [0.25, 0.46, 0.45, 0.94] }}
      >
        {children}
      </motion.div>
    </div>
  );
}

/* ─── audience card ─── */
function AudienceCard({
  icon: Icon,
  audience,
  body,
  delay = 0,
}: {
  icon: React.ElementType;
  audience: string;
  body: string;
  delay?: number;
}) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-10% 0px" });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 32 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay, ease: "easeOut" }}
      className="bg-primary rounded-4xl p-8 md:p-10 flex flex-col relative overflow-hidden h-full"
    >
      <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_center,var(--tw-gradient-stops))] from-white to-transparent" />
      <Icon className="text-white/80 w-10 h-10 mb-8 relative z-10" />
      <p className="text-white/60 text-xs font-medium uppercase tracking-widest mb-3 relative z-10">
        For {audience}
      </p>
      <p className="text-white/90 text-[15px] leading-relaxed relative z-10 grow">
        {body}
      </p>
    </motion.div>
  );
}

/* ─── feature pill ─── */
function FeaturePill({
  icon: Icon,
  label,
  desc,
}: {
  icon: React.ElementType;
  label: string;
  desc: string;
}) {
  return (
    <div className="flex items-start gap-4">
      <div className="w-10 h-10 shrink-0 rounded-xl bg-primary/10 flex items-center justify-center mt-0.5">
        <Icon size={18} className="text-primary" />
      </div>
      <div>
        <p className="text-brand-dark font-semibold text-[15px] mb-1">{label}</p>
        <p className="text-brand-gray text-[14px] leading-relaxed">{desc}</p>
      </div>
    </div>
  );
}

/* ─── how-it-works video section ─── */
function HowItWorksSection() {
  const [playing, setPlaying] = useState(false);
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-10% 0px" });

  return (
    <section
      ref={ref}
      className="w-full bg-white pt-24 pb-32 px-4 md:px-12 flex flex-col items-center"
    >
      <div className="max-w-6xl mx-auto w-full">

        {/* Top row: heading left, body right — matching attachment layout */}
        <div className="flex flex-col md:flex-row gap-10 md:gap-16 mb-12 items-start">
          {/* Left: heading */}
          <div className="md:w-2/5">
            <RevealText
              className="text-[26px] md:text-[34px] font-bold leading-[1.15] tracking-tight text-brand-dark"
              delay={0}
            >
              How the Skill Passport Works
            </RevealText>
          </div>

          {/* Right: body copy */}
          <motion.div
            className="md:w-3/5"
            initial={{ opacity: 0, y: 16 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <p className="text-brand-gray text-[15px] leading-relaxed mb-4">
              The Skill Passport is Re-Skill Africa&apos;s competence infrastructure.
              Every certified skill is grounded in observable work — assessed
              against sectoral standards, portable across employers, and
              verifiable at source.
            </p>
            <p className="text-brand-gray text-[15px] leading-relaxed">
              Inside Skildustry enterprises, the Passport captures evidence
              generated by real production. The assessment is the market output —
              every claim traces back to what was built, measured, and delivered.
            </p>
          </motion.div>
        </div>

        {/* Full-width red card with inset video — matches attachment */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.75, delay: 0.3, ease: [0.25, 0.46, 0.45, 0.94] }}
          className="w-full bg-primary rounded-4xl p-6 md:p-10 relative overflow-hidden"
        >
          {/* Zigzag/vector pattern overlay — same as footer card */}
          <div className="absolute inset-0 bg-[url(/images/footer_card_vector.png)] opacity-25 pointer-events-none" />

          <div
            className="relative w-full aspect-video rounded-2xl overflow-hidden cursor-pointer group bg-black"
            onClick={() => !playing && setPlaying(true)}
          >
            {!playing ? (
              <>
                {/* <Image
                  src="/images/about-section-5.webp"
                  alt="How the Skill Passport works"
                  fill
                  className="object-cover object-top transition-transform duration-700 group-hover:scale-105"
                /> */}
                {/* Subtle dark vignette so play button pops */}
                <div className="absolute inset-0 bg-black/20 group-hover:bg-black/30 transition-colors duration-300" />

                {/* Play button — centered */}
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="w-16 h-16 rounded-full bg-primary flex items-center justify-center shadow-2xl group-hover:scale-110 transition-transform duration-300">
                    <div className="w-0 h-0 border-t-[10px] border-t-transparent border-b-[10px] border-b-transparent border-l-[18px] border-l-white ml-1" />
                  </div>
                </div>
              </>
            ) : (
              <video
                controls
                autoPlay
                className="w-full h-full object-cover"
              >
                <source src="/videos/skilldustry.mp4" type="video/mp4" />
                Your browser does not support the video tag.
              </video>
            )}
          </div>
        </motion.div>

      </div>
    </section>
  );
}

/* ════════════════════════════════════════════
   PAGE
════════════════════════════════════════════ */
export default function SkillPassportPage() {
  const heroRef = useRef(null);
  const explainedRef = useRef(null);
  const explainedInView = useInView(explainedRef, {
    once: true,
    margin: "-10% 0px",
  });

  return (
    <div className="bg-white min-h-screen">
      {/* ── HERO ──────────────────────────────── */}
      <section
        ref={heroRef}
        className="relative w-full min-h-screen flex flex-col justify-center overflow-hidden"
      >
        {/* Background */}
        <Image
          src="/images/skill-passport-hero.webp"
          alt="Skill Passport hero"
          fill
          className="object-cover"
          priority
        />
        <div className="absolute inset-0 bg-layout-overlay/60 mix-blend-multiply" />
        <div className="absolute inset-0 bg-black/10" />

        {/* Hero content — centered */}
        <div className="relative z-10 w-full max-w-4xl mx-auto px-8 md:px-12 flex flex-col items-center text-center -mt-16">
          {/* Badge */}
          <div className="overflow-hidden mb-6">
            <motion.div
              className="inline-flex items-center gap-2 text-white px-4 py-1.5 text-sm font-medium"
              initial={{ y: "110%" }}
              animate={{ y: "0%" }}
              transition={{ duration: 0.6, delay: 0.2, ease: [0.25, 0.46, 0.45, 0.94] }}
            >
              <Database size={14} />
              One Passport, Endless Opportunities
            </motion.div>
          </div>

          {/* H1 */}
          <div className="overflow-hidden mb-6">
            <motion.h1
              className="text-white text-[44px] md:text-[60px] lg:text-[74px] font-bold leading-[1.0] tracking-tight drop-shadow-md"
              initial={{ y: "100%" }}
              animate={{ y: "0%" }}
              transition={{ duration: 0.75, delay: 0.3, ease: [0.25, 0.46, 0.45, 0.94] }}
            >
              The Digital Skill <br className="hidden md:block" /> Passport
            </motion.h1>
          </div>

          {/* Subhead */}
          <div className="overflow-hidden mb-8">
            <motion.p
              className="text-white/85 text-[17px] md:text-[20px] font-normal leading-relaxed max-w-2xl"
              initial={{ y: "100%" }}
              animate={{ y: "0%" }}
              transition={{ duration: 0.7, delay: 0.42, ease: [0.25, 0.46, 0.45, 0.94] }}
            >
              Industry-standard credentials that certify what a person can produce.
            </motion.p>
          </div>

          {/* CTA */}
          <motion.div
            className="flex flex-col sm:flex-row items-center gap-4"
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.6 }}
          >
            <ActionButton variant="primary">See how it works</ActionButton>
          </motion.div>
        </div>

        {/* Bottom-right glassmorphism cards */}
        <div className="absolute bottom-6 right-8 lg:right-12 hidden lg:flex flex-col gap-3 w-[380px]">
          {[
            {
              icon: Shield,
              title: "Verifiable blockchain ID",
              sub: "Tamper-proof and instantly verifiable by employers.",
              delay: "0.2s",
            },
            {
              icon: RefreshCcw,
              title: "Updated in real-time",
              sub: "Continuously updated as you master new competencies.",
              delay: "0.4s",
            },
            {
              icon: Globe,
              title: "Global recognition",
              sub: "Recognised by African and international employers.",
              delay: "0.6s",
            },
          ].map(({ icon: Icon, title, sub, delay }) => (
            <div
              key={title}
              className="flex items-start gap-4 p-4 rounded-2xl bg-white/10 backdrop-blur-md border border-white/20 shadow-xl opacity-0"
              style={{
                animation: `fade-in-up 0.6s ease-out ${delay} forwards`,
              }}
            >
              <div className="text-white mt-0.5 opacity-90">
                <Icon size={20} strokeWidth={1.5} />
              </div>
              <div>
                <h3 className="text-white font-medium text-[14px] mb-0.5">{title}</h3>
                <p className="text-white/70 text-[12px] font-light">{sub}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── EXPLAINED (Passport Explained + Card) ─ */}
      <section
        ref={explainedRef}
        className="w-full bg-white pt-24 pb-28 px-4 md:px-12 flex flex-col items-center"
      >
        <div className="max-w-6xl mx-auto w-full flex flex-col lg:flex-row gap-16 items-center">
          {/* Left: text + features */}
          <div className="flex-1 flex flex-col">
            {/* Badge */}
            <div className="overflow-hidden inline-block mb-6">
              <motion.div
                className="inline-flex items-center gap-2 border border-primary text-primary rounded-full px-4 py-1.5 text-sm font-medium"
                initial={{ y: "110%" }}
                animate={explainedInView ? { y: "0%" } : {}}
                transition={{ duration: 0.6, ease: [0.25, 0.46, 0.45, 0.94] }}
              >
                <BookMarked size={15} />
                Skill Passport Explained
              </motion.div>
            </div>

            {/* Headline */}
            <div className="overflow-hidden mb-6">
              <motion.h2
                className="text-[28px] md:text-[40px] font-bold leading-[1.1] tracking-tight text-brand-dark"
                initial={{ y: "100%" }}
                animate={explainedInView ? { y: "0%" } : {}}
                transition={{ duration: 0.7, delay: 0.1, ease: [0.25, 0.46, 0.45, 0.94] }}
              >
                The Skill Passport is the core digital infrastructure of Re-Skill Africa.
              </motion.h2>
            </div>

            <motion.p
              className="text-brand-gray text-[16px] leading-relaxed mb-10"
              initial={{ opacity: 0 }}
              animate={explainedInView ? { opacity: 1 } : {}}
              transition={{ duration: 0.6, delay: 0.25 }}
            >
              The Digital Skill Passport is Re-Skill Africa&apos;s competence
              infrastructure. Every certified skill is grounded in observable
              work — assessed against sectoral standards, portable across
              employers, and verifiable at source.
            </motion.p>

            {/* Feature grid */}
            <motion.div
              className="grid grid-cols-1 sm:grid-cols-2 gap-6"
              initial={{ opacity: 0, y: 20 }}
              animate={explainedInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.35 }}
            >
              <FeaturePill
                icon={Shield}
                label="Verifiable blockchain ID"
                desc="Your credentials are secured by blockchain technology, making them tamper-proof and instantly verifiable by employers."
              />
              <FeaturePill
                icon={Users}
                label="Matched to opportunities"
                desc="Your credentials are matched to real job opportunities across partner employers and sectors."
              />
              <FeaturePill
                icon={RefreshCcw}
                label="Updated in real-time"
                desc="Your Skill Passport is continuously updated by partners as you master new competencies."
              />
              <FeaturePill
                icon={Globe}
                label="Global recognition"
                desc="Your credentials are recognised by African and international employers, opening doors across borders."
              />
            </motion.div>
          </div>

          {/* Right: animated passport card */}
          <div className="flex-1 flex justify-center lg:justify-end">
            <SkillPassportCard />
          </div>
        </div>
      </section>

      {/* ── AUDIENCE (3 red cards) ──────────────── */}
      <section className="w-full bg-gray-50 py-24 px-4 md:px-12 flex flex-col items-center">
        <div className="max-w-6xl mx-auto w-full">
          {/* Section header */}
          <div className="flex flex-col items-center text-center mb-16">
            <RevealText
              className="inline-flex items-center gap-2 border border-primary text-primary rounded-full px-4 py-1.5 text-sm font-medium mb-6 w-fit"
              delay={0}
            >
              <CheckCircle size={15} />
              What It Means
            </RevealText>
            <RevealText
              className="text-[30px] md:text-[44px] font-bold leading-[1.1] tracking-tight text-brand-dark max-w-2xl"
              delay={0.1}
            >
              What the Passport means to each audience.
            </RevealText>
          </div>

          {/* Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full">
            <AudienceCard
              icon={Shield}
              audience="the certified"
              body="It is a durable record of what you can produce — portable, verifiable, and yours."
              delay={0}
            />
            <AudienceCard
              icon={BarChart3}
              audience="employers"
              body="It is a reliable signal of what a hire can deliver on day one. Every claim on the Passport traces back to observable work assessed against sectoral standards."
              delay={0.12}
            />
            <AudienceCard
              icon={Database}
              audience="funders and partners"
              body="It is an audit-grade evidence chain from training to deployment. Every cohort dollar can be traced through demand signal, cohort composition, competence assessment, and outcome."
              delay={0.24}
            />
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS (video) ───────────────── */}
      <HowItWorksSection />

      {/* ── FINAL CTA ─────────────────────────── */}
      <section className="w-full bg-white pt-4 pb-70  px-4 md:px-12 flex flex-col items-center text-center">
        <div className="max-w-3xl mx-auto">
          <RevealText
            className="text-[28px] md:text-[40px] lg:text-[48px] font-bold leading-[1.15] tracking-tight text-brand-dark mb-8"
            delay={0}
          >
            Your competence, documented.{" "}
            <span className="text-primary">Yours to carry.</span>
          </RevealText>
          <motion.p
            className="text-brand-gray text-[16px] md:text-[18px] leading-relaxed mb-10 max-w-2xl mx-auto"
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            Join a cohort inside a Skildustry enterprise and begin building your
            Passport from day one of production.
          </motion.p>
          <motion.div
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <ActionButton variant="primary">Apply to a cohort</ActionButton>
            <ActionButton variant="secondary">Learn about Skildustry</ActionButton>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
